### PR TITLE
Added pre-commit hook

### LINKED ISSUE #110: Set up pre-commit hook for markdown linter
## Feature description

We've had some PR merges that failed build due to Markdown formatting issues.  

I'm not sure how to set up a precommit hook, but if we could use a `markdownlint` one, that would be helpful for preventing errors.

### PR DESCRIPTION
**Pull request by Nyette**
# Description

Added pre-commit hook.

Fixes #110 

## Type of change

- [x] New feature

# How Has This Been Tested?

I purposely tried to commit a file that didn't follow markdown rules and the commit was automatically aborted. 

**Test Configuration**: N/A
* Browser: N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Nyette** [comment]
We will have to configure `markdownlint` , so that it tells us what needs to be fixed. At the moment, the commit is just aborted.

**Comment by kelseyhuse30** [comment]
Thank you @Nyette ! I tried testing this and put in some incorrect indention in the frontmatter data and it didn't catch it :( This is what I tried:

```yaml
blm_statements:
  - url: https://media.gm.com/media/us/en/gm/home.detail.html/content/Pages/news/us/en/2020/jun/0605-support.html
    date_posted: 2020-06-05
  raw_text: blahhhhh
   hello
```

I tested out this one instead and it seemed to work, do you wanna try it? Since the front-matter data is YAML rather than Markdown.  I guess I assumed Markdown linters would catch errors in the front-matter which is where most of our errors happen.

https://www.npmjs.com/package/yaml-lint

**Comment by Nyette** [comment]
Yeah, we can try it! I'll set it up as soon as I can

**Comment by Nyette** [comment]
It should work now!

I tried to commit the following just like you did:

```yaml
blm_statements:
  - url: https://media.gm.com/media/us/en/gm/home.detail.html/content/Pages/news/us/en/2020/jun/0605-support.html
    date_posted: 2020-06-05
  raw_text: blahhhhh
   hello
```
It aborted the commit, telling me:

```
bad indentation of a mapping entry at line 6, column 3:
       raw_text: blahhhhh
       ^
```

**Review by kelseyhuse30 — APPROVED** [review]

**Comment by kelseyhuse30** [comment]
@Nyette yessssss, awesome!! Thanks for taking this one on.

**Pull request merged**
