### PR TITLE
initial database creation script and instructions

### LINKED ISSUE #4: Set up a free postgresql database on Heroku

### PR DESCRIPTION
**Pull request by greendinosaur**
# Description

I've provided guidance on setting up a new postgres database on Heroku with the required scheme. The changes include:
1. A SQL file containing the table definitions. This has been amended from an initial one to support postgres.
2. A guidance note on creating a new database with the desired tables inside Heroku

Fixes #4

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I've tested this by:
- creating a new app on Heroku
- following the guidance notes and executing on my development machine
- I develop on a Mac so used the pgsql CLI tool to connect to the postgres database

# Checklist:

I haven't added any tests or amended existing ones as I imagine the database creation is a one-off exercise. Updates will likely need to be treated differently and a tool such as Flyway may be needed. I've suggested executing a postgres command to demonstrate the new tables have been created correctly.

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by kelseyhuse30 — APPROVED** [review]
Absolutely amazing @greendinosaur . Thank you for taking the schema and giving it life! I am going to merge this in and run through the instructions within the next week.  🎉 🎉

**Comment by greendinosaur** [comment]
Let me know if you have any issues getting it up and running on Heroku. Happy to help.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kelseyhuse30** [comment]
@greendinosaur THIS WAS SO EASY.  Took me about 5min to set up.  Thank you, thank you, thank you!!

**Comment by greendinosaur** [comment]
Glad it worked. The hard part is maintaining the schema going forward and deploying changes that the app requires. There are tools that can help such as flyway.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
