### PR TITLE
Better Responsive Homepage

### PR DESCRIPTION
**Pull request by tanmayhinge**
Added a few better homepage elements

### CODE REVIEW

**Comment by ravenclaw1999** [comment]
Hi, how come you closed the PR? Was it because I suggested we would be using the 11ty framework?

**Comment by tanmayhinge** [comment]
hey! yes i closed it because as you were planning eleventy, i can reopen if you need

**Comment by ravenclaw1999** [comment]
Thanks, that makes sense. We need a lot help building this project, so thanks for contributing!

**Comment by ravenclaw1999** [comment]
Actually, could you please reopen it?

**Comment by tanmayhinge** [comment]
sure wait, i deleted the remote, will have to make a new remote and new pr, would take about 5 mins

**Pull request closed without merging**
